CI: build TinyXML manually on macOS due to deprecation.
On macOS, TinyXML is now deprecated by Homebrew:

    Error: tinyxml has been disabled because it is deprecated upstream! It was disabled on 2025-06-03.

TinyXML has not been updated since 2011, with unfixed security
vulnerability, so the deprecation is justified. But TinyXML 2
has a different API, so it's not possible to fix the problem
in the short term.

As a workaround, build TinyXML 1 from source manually (with
custom patches and fixes collected from Homebrew and AlpineLinux's
repos, with modification).

Signed-off-by: Yifeng Li <tomli@tomli.me>